stages:
    - format
    - test

before_script:
   - python -V
   - python -m venv venv
   - source venv/bin/activate
   - pip install -U pip
   - pip install .[tests]

format:py38:
    image: python:3.8
    stage: format
    script:
        - pytest -m format

unit_test:py38:
    image: python:3.8
    stage: test
    script:
        - pytest -m unit --durations 10


format:py39:
    image: python:3.9
    stage: format
    script:
        - pytest -m format

unit_test:py39:
    image: python:3.9
    stage: test
    script:
        - pytest -m unit --durations 10


format:py310:
    image: python:3.10
    stage: format
    script:
        - pytest -m format

unit_test:py310:
    image: python:3.10
    stage: test
    script:
        - pytest -m unit --durations 10


format:py311:
    image: python:3.11
    stage: format
    script:
        - pytest -m format

unit_test:py311:
    image: python:3.11
    stage: test
    script:
        - pytest -m unit --durations 10
